### PR TITLE
refactor(envs,cli)!: envs first cli

### PR DESCRIPTION
**Pull request by Yohe-Am**
- Re-structure CLI around environments.
- Basic tests for envs.

### Motivation and context

#24 and #46 

### Migration notes

- `ghjk ports sync` has been replaced by a new suite of commands under `ghjk envs` and `ghjk sync`.
- This PR breaks the install identification scheme. Fully remove all `.ghjk` dirs and `~/.local/share/ghjk` to avoid any problems and bloat.

### Checklist

- [x] The change come with new or modified tests
- [x] Hard-to-understand functions have explanatory comments
- [x] End-user documentation is updated to reflect the change

### CODE REVIEW

**Review by Yohe-Am — COMMENTED** [review]
Read [here](https://github.com/metatypedev/ghjk/blob/feat/envs-cli/README.md#environments) for an overview of what the current CLI experience looks like. 

This PR is stacked on #46 but reading that is a not a necessity to grasp this.

**Comment by Yohe-Am** [comment]
Until https://github.com/dsherret/dax/pull/264 gets merged upstream, I've decided to vendor dax with the patched applied insie this repo.

**Comment by Yohe-Am** [comment]
Aand, I had to publish https://jsr.io/@ghjk/dax because vendoring wan't enough as well. Dax is critical to the ghjk experience so might as well. We might want to modify more of it.

**Comment by Yohe-Am** [comment]
Aand, I had to publish https://jsr.io/@ghjk/dax because vendoring wan't enough as well. Dax is critical to the ghjk experience so might as well. We might want to modify more of it.

**Review by zifeo — COMMENTED** [review]
lgtm

**Pull request merged**
